config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  resources :addresses
  resources :locations
  get 'jobs/find_by_category'
  get 'jobs/find_my_jobs'
  get 'jobs/search_jobs'
  resources :jobs 
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'upload_cv', to: "cv#upload_cv"
  patch 'upload_cv', to: 'cv#update'
  resources :employement_types
  resources :career_levels
  resources :job_search_titles
  resources :job_categories
  resources :employers
  root 'jobs#index'
  get 'home/index'
  get 'home/about'
  get 'home/cv_tips'
  get 'home/interview_tips'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job_category.rb
class JobCategory < ApplicationRecord
	has_many :jobs
end

app/controllers/job_categories_controller.rb
class JobCategoriesController < ApplicationController
  before_action :set_job_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 
  # GET /job_categories or /job_categories.json
  def index
    @job_categories = JobCategory.all
  end

  # GET /job_categories/1 or /job_categories/1.json
  def show
  end

  # GET /job_categories/new
  def new
    @job_category = JobCategory.new
  end

  # GET /job_categories/1/edit
  def edit
  end

  # POST /job_categories or /job_categories.json
  def create
    @job_category = JobCategory.new(job_category_params)

    respond_to do |format|
      if @job_category.save
        format.html { redirect_to @job_category, notice: "Job category was successfully created." }
        format.json { render :show, status: :created, location: @job_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_categories/1 or /job_categories/1.json
  def update
    respond_to do |format|
      if @job_category.update(job_category_params)
        format.html { redirect_to @job_category, notice: "Job category was successfully updated." }
        format.json { render :show, status: :ok, location: @job_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_categories/1 or /job_categories/1.json
  def destroy
    @job_category.destroy
    respond_to do |format|
      format.html { redirect_to job_categories_url, notice: "Job category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_category
      @job_category = JobCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_category_params
      params.require(:job_category).permit(:name)
    end
end

app/helpers/job_categories_helper.rb
module JobCategoriesHelper
end

app/views/job_categories/_form.html.erb
<%= form_with(model: job_category) do |form| %>
  <% if job_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job_category.errors.count, "error") %> prohibited this job_category from being saved:</h2>

      <ul>
        <% job_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/job_categories/edit.html.erb
<h1>Editing Job Category</h1>

<%= render 'form', job_category: @job_category %>

<%= link_to 'Show', @job_category %> |
<%= link_to 'Back', job_categories_path %>

app/views/job_categories/index.html.erb
<h1>Job Categories</h1>
<%= link_to 'New Job Category', new_job_category_path %>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @job_categories.each do |job_category| %>
      <tr>
        <td><%= job_category.name %></td>
        <td><%= link_to 'Show', job_category %></td>
        <td><%= link_to 'Edit', edit_job_category_path(job_category) %></td>
        <td><%= link_to 'Destroy', job_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Job Category', new_job_category_path %>
<br>

app/views/job_categories/new.html.erb
<h1>New Job Category</h1>

<%= render 'form', job_category: @job_category %>

<%= link_to 'Back', job_categories_path %>

app/views/job_categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @job_category.name %>
</p>

<%= link_to 'Edit', edit_job_category_path(@job_category) %> |
<%= link_to 'Back', job_categories_path %>