config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  resources :addresses
  resources :locations
  get 'jobs/find_by_category'
  get 'jobs/find_my_jobs'
  get 'jobs/search_jobs'
  resources :jobs 
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'upload_cv', to: "cv#upload_cv"
  patch 'upload_cv', to: 'cv#update'
  resources :employement_types
  resources :career_levels
  resources :job_search_titles
  resources :job_categories
  resources :employers
  root 'jobs#index'
  get 'home/index'
  get 'home/about'
  get 'home/cv_tips'
  get 'home/interview_tips'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/career_level.rb
class CareerLevel < ApplicationRecord
	has_many :jobs
	
end

app/controllers/career_levels_controller.rb
class CareerLevelsController < ApplicationController
  before_action :set_career_level, only: %i[ show edit update destroy ]
  before_action :authenticate_user! 
  # GET /career_levels or /career_levels.json
  def index
    @career_levels = CareerLevel.all
  end

  # GET /career_levels/1 or /career_levels/1.json
  def show
  end

  # GET /career_levels/new
  def new
    @career_level = CareerLevel.new
  end

  # GET /career_levels/1/edit
  def edit
  end

  # POST /career_levels or /career_levels.json
  def create
    @career_level = CareerLevel.new(career_level_params)

    respond_to do |format|
      if @career_level.save
        format.html { redirect_to @career_level, notice: "Career level was successfully created." }
        format.json { render :show, status: :created, location: @career_level }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @career_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /career_levels/1 or /career_levels/1.json
  def update
    respond_to do |format|
      if @career_level.update(career_level_params)
        format.html { redirect_to @career_level, notice: "Career level was successfully updated." }
        format.json { render :show, status: :ok, location: @career_level }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @career_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /career_levels/1 or /career_levels/1.json
  def destroy
    @career_level.destroy
    respond_to do |format|
      format.html { redirect_to career_levels_url, notice: "Career level was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_career_level
      @career_level = CareerLevel.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def career_level_params
      params.require(:career_level).permit(:name)
    end
end

app/helpers/career_levels_helper.rb
module CareerLevelsHelper
end

app/views/career_levels/_form.html.erb
<%= form_with(model: career_level) do |form| %>
  <% if career_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(career_level.errors.count, "error") %> prohibited this career_level from being saved:</h2>

      <ul>
        <% career_level.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/career_levels/edit.html.erb
<h1>Editing Career Level</h1>

<%= render 'form', career_level: @career_level %>

<%= link_to 'Show', @career_level %> |
<%= link_to 'Back', career_levels_path %>

app/views/career_levels/index.html.erb
<h1>Career Levels</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @career_levels.each do |career_level| %>
      <tr>
        <td><%= career_level.name %></td>
        <td><%= link_to 'Show', career_level %></td>
        <td><%= link_to 'Edit', edit_career_level_path(career_level) %></td>
        <td><%= link_to 'Destroy', career_level, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Career Level', new_career_level_path %>

app/views/career_levels/new.html.erb
<h1>New Career Level</h1>

<%= render 'form', career_level: @career_level %>

<%= link_to 'Back', career_levels_path %>

app/views/career_levels/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @career_level.name %>
</p>

<%= link_to 'Edit', edit_career_level_path(@career_level) %> |
<%= link_to 'Back', career_levels_path %>