config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  resources :addresses
  resources :locations
  get 'jobs/find_by_category'
  get 'jobs/find_my_jobs'
  get 'jobs/search_jobs'
  resources :jobs 
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'upload_cv', to: "cv#upload_cv"
  patch 'upload_cv', to: 'cv#update'
  resources :employement_types
  resources :career_levels
  resources :job_search_titles
  resources :job_categories
  resources :employers
  root 'jobs#index'
  get 'home/index'
  get 'home/about'
  get 'home/cv_tips'
  get 'home/interview_tips'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :career_level, :optional => true
	belongs_to :employement_type, :optional => true
	belongs_to :employer, :optional => true
	belongs_to :job_category, :optional => true
	belongs_to :destination, :optional => true
	belongs_to :user, :optional => true
	has_rich_text :howtoApply
	has_rich_text :discription
	has_rich_text :jobRequirements
	#validates :Employer_id, :presence => true
	#validates :is_approved, :presence => true
	#validates :createdBy_id, :presence => true
end

app/controllers/jobs_controller.rb
require 'date'
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy]
  before_action :authenticate_user! , only: %i[edit update destroy new create]
  JOBS_PER_PAGE=5
  # GET /jobs or /jobs.json
  
  def index
    @page = params.fetch(:page,0).to_i
    @JobCategory_id = params.fetch(:JobCategory_id,0).to_i
    
    @jobsPageCount=Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).all.count/JOBS_PER_PAGE
    @jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(id: :desc).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)
  end

  def find_by_category
   @page = params.fetch(:page,0).to_i
    @JobCategory_id = params.fetch(:JobCategory_id,0).to_i
    @category_name=JobCategory.find(@JobCategory_id).name

    @jobsPageCount=(Job.where("\"deadlineDate\" >= :date and \"JobCategory_id\" = :jobcategory and \"is_approved\"=true",  date: Date.today, jobcategory: @JobCategory_id).all.count/JOBS_PER_PAGE) 
    @jobs = Job.where("\"deadlineDate\" >= :date and \"JobCategory_id\" = :jobcategory",  date: Date.today, jobcategory: @JobCategory_id).order(id: :desc).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"JobCategory_id\" = :jobcategory",  date: Date.today, jobcategory: @JobCategory_id).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)
  end
  
  def search_jobs
    @page = params.fetch(:page,0).to_i
    @JobCategory_id = params.fetch(:search,0).to_i
    
    @jobsPageCount=Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).all.count/JOBS_PER_PAGE
    @jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(id: :desc).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)
  end
  
  def find_my_jobs
    @page = params.fetch(:page,0).to_i
    @JobCategory_id = params.fetch(:JobCategory_id,0).to_i
    
    @jobsPageCount=Job.where("\"createdBy_id\" = :publisher_id",  publisher_id: current_user.id).all.count/JOBS_PER_PAGE
    @jobs = Job.where("\"createdBy_id\" = :publisher_id",  publisher_id: current_user.id).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)
end

  # GET /jobs/1 or /jobs/1.json
  def show
      @page = params.fetch(:page,0).to_i
      @JobCategory_id = params.fetch(:JobCategory_id,0).to_i
      
        @jobsPageCount=Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).all.count/JOBS_PER_PAGE
    @jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(id: :desc).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)

      if @job.numberOfviews == nil    
        @job.numberOfviews =1 
        @job.save
      else 
        @job.numberOfviews +=1 
        @job.save
      end
  end

  # GET /jobs/new
  def new
     @page = params.fetch(:page,0).to_i
    @JobCategory_id = params.fetch(:JobCategory_id,0).to_i
    
     @jobsPageCount=Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).all.count/JOBS_PER_PAGE
    @jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(id: :desc).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)

    
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
     @page = params.fetch(:page,0).to_i
      @JobCategory_id = params.fetch(:JobCategory_id,0).to_i
      
       @jobsPageCount=Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).all.count/JOBS_PER_PAGE
    @jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(id: :desc).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)

     
  end

  # POST /jobs or /jobs.json
  def create
    @page = params.fetch(:page,0).to_i
      @JobCategory_id = params.fetch(:JobCategory_id,0).to_i
      
      @jobsPageCount=Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).all.count/JOBS_PER_PAGE
    @jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(id: :desc).offset(@page * JOBS_PER_PAGE).limit(JOBS_PER_PAGE)
    @job_categories = JobCategory.all
    @featured_jobs = Job.where("\"deadlineDate\" >= :date and \"is_approved\"=true",  date: Date.today).order(numberOfviews: :desc).limit(JOBS_PER_PAGE)


    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created. It will be posted once site administrators approved your job." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :Salary, :postedDate, :deadlineDate, :discription, :jobRequirements, :howtoApply, :numberOfviews, :Location_id, :CareerLevel_id, :EmployementType_id, :Employer_id, :JobCategory_id, :is_approved,:createdBy_id, :destination_id, :search)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

              <div class="field form-group">
                <%= form.label :title %>
                <%= form.text_field :title ,class:"form-control" %>
              </div>

              <div class="field form-group">
                <%= form.label :Salary %>
                <%= form.text_field :Salary ,class:"form-control" %>
              </div>

              <div class="field form-group">
                <%= form.label "deadline Date" %>
                <%= form.date_field :deadlineDate ,class:"form-control" %>
              </div>
              <br>
              <div class="field form-group">
                <%= form.label :discription %>
                <%= form.rich_text_area :discription ,class:"form-control" %>
              </div>
              <br>
              <div class="field form-group">
                <%= form.label "Job Requirements" %>
                <%= form.rich_text_area :jobRequirements ,class:"form-control" %>
              </div>
              <br>
              <div class="field form-group">
                <%= form.label "How To Apply" %>
                <%= form.rich_text_area :howtoApply ,class:"form-control" %>
              </div>
              <br>

              <div class="field form-group">
                <%= form.label "Location" %>
                <%= form.collection_select :destination_id, Destination.all, :id, :City, include_blank: true  ,class:"form-control custom-select" %>
              </div>
              <br>
              <div class="field form-group">
                  <%= form.label "Career Level" %>
                  <%= form.collection_select :CareerLevel_id, CareerLevel.all, :id, :name, include_blank: true ,class:"form-control"  %>
                  
              </div>
              <br>
              <% if current_user.is_manager %>
                <div class="field form-group">
                    <%= form.label "Employement Type" %>
                    <%= form.collection_select :EmployementType_id, EmployementType.all, :id, :name, include_blank: true ,class:"form-control"  %>
                </div>
                <br>
              <% end %>
              <div class="field form-group">
                  <%= form.label "Employer" %>
                  <%= form.collection_select :Employer_id, Employer.all, :id, :name, include_blank: true ,class:"form-control custom-select"  %>
                 
              </div>
              <br>
              <div class="field form-group">
                  <%= form.label "Job Category" %>
                  <%= form.collection_select :JobCategory_id, JobCategory.all, :id, :name, include_blank: true ,class:"form-control"  %>
                 
              </div>
              <br>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>

<% end %>

app/views/jobs/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item"><%= link_to "Back to job detail" , @job %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @job.title %></li>
  </ol>
</nav>
   
      <div class="container-fluid">
         <div class="row">
            <%= render 'layouts/leftsidebar'%>
            	<div class="col-7">
            		<h1>Modifying Job</h1>

					<%= render 'form', job: @job %>

					<%= link_to 'Show', @job %> |
					<%= link_to 'Back', jobs_path %>
				<br><br><br>
				</div>	
		 <%= render 'layouts/rightsidebar' %>
    </div>

</div>

app/views/jobs/find_by_category.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Full Jobs list', root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @category_name %> jobs in Ethiopia</li>
  </ol>
</nav>
<div class="container-fluid">
    <div class="row">
        <%= render 'layouts/leftsidebar'%>
        <div class="col-7">
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-end">
                <% if @page > 0 %>
                    <li class="page-item"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% end %>
                

                <% if @page < @jobsPageCount %>
                    <li class="page-item"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% end %>
                
              </ul>
            </nav>
            <table class="table table-responsive table-hover" width="100%">
               <thead>
               </thead>
               <tbody>
                 
                <% @jobs.each do |job| %>
                   <tr> 
                        <td width="65%">
                          
                              <%= link_to job.title, job, class:"link-primary fs-6" %><br>
                                <p class="text-muted">
                          <i class="fa fa-map-marker mg5r"></i> <% if Destination.where(:id=> job.destination_id).first !=nil %>
                                <%= Destination.where(:id=> job.destination_id).first.City %>,
                                <%= Destination.where(:id=> job.destination_id).first.Region %>
                                <% end %><br>
                          <i class="mg5r fa fa-envelope"></i> Employment Type: <%= EmployementType.where(:id => job.EmployementType_id).pluck(:name).first() %><br>
                          <i class="mg5r fa fa-briefcase"></i> Level: <%= CareerLevel.where(:id => job.CareerLevel_id).pluck(:name).first() %> 
                            </p>
                             <%= link_to "View details" , job, class:"btn btn-link" %>
                           
                        </td>
                        <td width="35%">
                            <table class="table table-responsive">
                            <tr>
                                <td>   
                                    <p class="text-danger">
                                            <i class="mg5r fa fa-clock"></i> Deadline: <%= job.deadlineDate %> 
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td> 
                                <%
                                    if job.Employer_id != nil 
                                %>
                                <%= 
                                    image_tag rails_blob_url(Employer.where("id = ?" , job.Employer_id).first.logo),width:"70px",height:"70px" %>
                                <%
                                    end
                                %> 
                                </td>
                            </tr>
                            </table>
                        </td>       
                                
                    </tr> 
                        

                    
                <% end %>
              </tbody>
            </table>
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-end">
                <% if @page > 0 %>
                    <li class="page-item"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% end %>
                

                <% if @page < @jobsPageCount %>
                    <li class="page-item"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% end %>
                
              </ul>
            </nav>
        </div>
       <%= render 'layouts/rightsidebar' %>
    </div>

</div>

app/views/jobs/find_my_jobs.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
     <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Full Jobs list', root_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Jobs posts by you</li>
  </ol>
</nav>
<div class="container-fluid">
    <div class="row">
        <%= render 'layouts/leftsidebar'%>
        <% if @jobs.count>0 %>
        <div class="col-7">
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-end">
                <% if @page > 0 %>
                    <li class="page-item"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% end %>
                

                <% if @page < @jobsPageCount %>
                    <li class="page-item"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% end %>
                
              </ul>
            </nav>
            <table class="table table-responsive table-hover" width="100%">
               <thead>
               </thead>
               <tbody>
                 
                <% @jobs.each do |job| %>
                   <tr> 
                        <td width="65%">
                          
                              <%= link_to job.title, job, class:"link-primary fs-6" %><br>
                                <p class="text-muted">
                          <i class="fa fa-map-marker mg5r"></i> <% if Destination.where(:id=> job.destination_id).first !=nil %>
                                <%= Destination.where(:id=> job.destination_id).first.City %>,
                                <%= Destination.where(:id=> job.destination_id).first.Region %>
                                <% end %><br>
                          <i class="mg5r fa fa-envelope"></i> Employment Type: <%= EmployementType.where(:id => job.EmployementType_id).pluck(:name).first() %><br>
                          <i class="mg5r fa fa-briefcase"></i> Level: <%= CareerLevel.where(:id => job.CareerLevel_id).pluck(:name).first() %> 
                            </p>
                             <%= link_to "View details" , job, class:"btn btn-link" %>
                           
                        </td>
                        <td width="35%">
                            <table class="table table-responsive">
                            <tr>
                                <td>   
                                    <p class="text-danger">
                                            <i class="mg5r fa fa-clock"></i> Deadline: <%= job.deadlineDate %> 
                                    </p>
                                </td>
                            </tr>
                            <tr>
                                <td> 
                                <%
                                    if job.Employer_id != nil 
                                %>
                                <%= 
                                    image_tag rails_blob_url(Employer.where("id = ?" , job.Employer_id).first.logo),width:"70px",height:"70px" %>
                                <%
                                    end
                                %> 
                                </td>
                            </tr>
                            </table>
                        </td>       
                                
                    </tr> 
                        

                    
                <% end %>
              </tbody>
            </table>
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-end">
                <% if @page > 0 %>
                    <li class="page-item"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Previous", jobs_find_by_category_path(page: @page-1) ,class:"page-link" %></li>
                <% end %>
                

                <% if @page < @jobsPageCount %>
                    <li class="page-item"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% else %>
                    <li class="page-item disabled"><%= link_to "Next", jobs_find_by_category_path(page: @page+1) ,class:"page-link" %></li>
                <% end %>
                
              </ul>
            </nav>
        </div>
        <% else %>
        <div class="col-7">
            <h3>You didn't post any jobs yet!</h3>
        </div>
        <% end %>
        
       <%= render 'layouts/rightsidebar' %>
    </div>

</div>

app/views/jobs/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
     <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Back to my jobs list', jobs_find_my_jobs_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Posting a job</li>
  </ol>
</nav>
   
      <div class="container-fluid">
         <div class="row">
            <%= render 'layouts/leftsidebar'%>
            	<div class="col-7">
					<h2>Post a Job</h2>

					<%= form_with(model: @job) do |form| %>
						  <% if @job.errors.any? %>
						    <div id="error_explanation">
						      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

						      <ul>
						        <% @job.errors.each do |error| %>
						          <li><%= error.full_message %></li>
						        <% end %>
						      </ul>
						    </div>
						  <% end %>

						  <div class="field form-group">
						    <%= form.label :title %>
						    <%= form.text_field :title ,class:"form-control" %>
						  </div>

						  <div class="field form-group">
						    <%= form.label :Salary %>
						    <%= form.text_field :Salary ,class:"form-control" %>
						  </div>

						  <div class="field form-group">
						    <%= form.label "deadline Date" %>
						    <%= form.date_field :deadlineDate ,class:"form-control" %>
						  </div>
						  <br>
						  <div class="field form-group">
						    <%= form.label :discription %>
						    <%= form.rich_text_area :discription ,class:"form-control" %>
						  </div>
						  <br>
						  <div class="field form-group">
						    <%= form.label "Job Requirements" %>
						    <%= form.rich_text_area :jobRequirements ,class:"form-control" %>
						  </div>
						  <br>
						  <div class="field form-group">
						    <%= form.label "How To Apply" %>
						    <%= form.rich_text_area :howtoApply ,class:"form-control" %>
						  </div>
						  <br>
						  <div class="field form-group">
						    <%= form.label "Location" %>
						    <%= form.collection_select :destination_id, Destination.all, :id, :City, include_blank: true  ,class:"form-control custom-select" %>
						  </div>
						  <br>
						  <div class="field form-group">
						      <%= form.label "Career Level" %>
						      <%= form.collection_select :CareerLevel_id, CareerLevel.all, :id, :name, include_blank: true ,class:"form-control"  %>
						      
						  </div>
						  <br>
						  <div class="field form-group">
						      <%= form.label "Employement Type" %>
						      <%= form.collection_select :EmployementType_id, EmployementType.all, :id, :name, include_blank: true ,class:"form-control"  %>
						  </div>
						  <br>
						  <% if current_user.is_manager %>
						  <div class="field form-group">
						      <%= form.label "Employer" %>
						      <%= form.collection_select :Employer_id, Employer.all, :id, :name, include_blank: true ,class:"form-control custom-select"  %>
						     
						  </div>
						  <br>
						  <% end %>
						  <div class="field form-group">
						      <%= form.label "Job Category" %>
						      <%= form.collection_select :JobCategory_id, JobCategory.all, :id, :name, include_blank: true ,class:"form-control"  %>
						     
						  </div>
						  <br>
						  <%= form.hidden_field :postedDate, value: DateTime.now %>
						  <%= form.hidden_field :numberOfviews, value: 0 %>
						    
               			
						  <%= form.hidden_field :createdBy_id, value: current_user.id %>
					   		
					   		<% if user_signed_in? %>
				              <% if current_user.is_manager==true %>
				                 <%= form.hidden_field :is_approved, value: true %>
				               <% else %>
				                 <%= form.hidden_field :is_approved, value: false %>
				               <% end %>
				               <% end %>
						  
						  <div class="actions">
						    <%= form.submit class:"btn btn-primary" %>
						  </div>

						<% end %>

					<br>
					<%= link_to 'Back', jobs_path %>
					<br><br><br>
				</div>	
		 <%= render 'layouts/rightsidebar' %>
    </div>

</div>

app/views/jobs/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
    <li class="breadcrumb-item"><%= link_to 'Full Jobs list', root_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @job.title %></li>
  </ol>
</nav>
<p>
   <div class="container-fluid">
         <div class="row">
            <%= render 'layouts/leftsidebar'%>
              <div class="col-7">
               <main class="">
                <div class="box shadow-sm  rounded bg-white mb-3">
                  <div class="box-title border-bottom p-3">
                    <h6 class="m-0 listingInfoHeader"><%= @job.title %></h6>
                  </div>
                  <div class=" p-3">
                   
                  <p>
                    <p>
                  <strong>Salary:</strong>
                  <%= @job.Salary %>
                </p>

                <p>
                  <strong>Posted Date:</strong>
                  <%= @job.postedDate %>
                </p>

                <p>
                  <strong>Deadlinedate:</strong>
                  <%= @job.deadlineDate %>
                </p>
                <p>
                  <strong>Job Category:</strong>
                  <% if JobCategory.where(:id=> @job.JobCategory_id).first !=nil %>
                  <%= JobCategory.where(:id=> @job.JobCategory_id).first.name %>
                  <% end %>
                </p>
                <p>
                  <strong>Career Level:</strong>
                  <% if CareerLevel.where(:id=> @job.CareerLevel_id).first !=nil %>
                  <%= CareerLevel.where(:id=> @job.CareerLevel_id).first.name %>
                  <% end %>
                </p>
                <p>
                  <strong>Employement Type:</strong>
                  <% if EmployementType.where(:id=> @job.EmployementType_id).first !=nil %>
                  <%= EmployementType.where(:id=> @job.EmployementType_id).first.name %>
                  <% end %>
                </p>
                 <p>
                  <strong>Job Location:</strong>
                  <% if Destination.where(:id=> @job.destination_id).first !=nil %>
                  <%= Destination.where(:id=> @job.destination_id).first.City %>,
                  <%= Destination.where(:id=> @job.destination_id).first.Region %>
                  <% end %>

                <p>
                  <strong>Job Views:</strong>
                  <%= @job.numberOfviews %>
                </p>
                  </p>
                  </div>
                </div>


              <div class="box shadow-sm  rounded bg-white mb-3">
                  <div class="box-title border-bottom p-3">
                    <h6 class="m-0 listingInfoHeader">Job Discription</h6>
                  </div>
                  <div class=" p-3">
                    <p><%= @job.discription %></p>
                  </div>
                </div>
                <div class="box shadow-sm  rounded bg-white mb-3"><div class="box-title border-bottom p-3">
                <h6 class="m-0 listingInfoHeader">Job Requirements</h6></div><div class="box-body p-3"><p></p>
                <p><%= @job.jobRequirements %></p></div></div>
                <div class="box shadow-sm  rounded bg-white mb-3"><div class="box-title border-bottom p-3">
                <h6 class="m-0 listingInfoHeader">How to Apply</h6></div><div class="box-body p-3"><div class="flex-row flex-wrap flex-align-start flex-vertical-center"></div><div class="box-body p-3"><p></p><p>
                <%= @job.howtoApply %></p><p>&nbsp;</p><p></p></div></div></div>
              </main>
              <% if user_signed_in? %>
              <% if current_user.is_manager==true or current_user.id==@job.createdBy_id %>
                 <%= link_to 'Edit', edit_job_path(@job), class:"btn btn-secondary" %>
               <% end %>
               <% end %>   
              <%= link_to 'Back', jobs_path %>
              <br>
          </div>  
         <%= render 'layouts/rightsidebar'%>
    </div>

</div>
<br>