config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  resources :addresses
  resources :locations
  get 'jobs/find_by_category'
  get 'jobs/find_my_jobs'
  get 'jobs/search_jobs'
  resources :jobs 
  devise_for :users, controllers: { sessions: 'users/sessions' }
  get 'upload_cv', to: "cv#upload_cv"
  patch 'upload_cv', to: 'cv#update'
  resources :employement_types
  resources :career_levels
  resources :job_search_titles
  resources :job_categories
  resources :employers
  root 'jobs#index'
  get 'home/index'
  get 'home/about'
  get 'home/cv_tips'
  get 'home/interview_tips'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<footer class="mainfooter" role="contentinfo">
  <div class="footer-middle">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>About & Contact Details</h4>
              <p >Ethiopian Job Portal is focused on giving an easier and online tool you need to find the right and latest Job openings throughout Ethiopia.

                        You can choose from our wide selection of Jobs on display. Just find what you need, we can display according to your needs.

              <br>
              +251 917 498840<br>
              +251 xxx xxxxxx<br>
              kaleb.takele0810@gmail.com
            </p>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Information</h4>
          <ul class="list-unstyled">
            <li><%= link_to 'About Us', home_about_path %></li>
            <li><a href="#">Contact Us</a></li>
            <li><a href="#">Privacy Policy</a></li>
            <li><a href="#">Terms & Conditions</a></li>
            <li><a href="#">FAQs</a></li>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Job Seekers & Employers</h4>
          <ul class="list-unstyled">
            <li><%= link_to 'Sign up', new_user_registration_path %></li>
            <li><%= link_to 'Sign in', new_user_session_path %></li>
            <li><%= link_to 'Apply for job', new_user_session_path%></li>
            <li><%= link_to 'Post a Job', new_job_path %></li>
            <li>
              <a href="#"></a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-3">
        <h4>Follow Us</h4>
            <ul class="social-network social-circle">
             <li><a href="#" class="icoFacebook" title="Facebook"><i class="fa fa-facebook"></i></a></li>
             <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
            </ul>       
    </div>
    </div>
  <div class="row">
    <div class="col-md-12 copy">
      <p class="text-center">&copy; Copyright 2021 - LifeScope Computer Solutions.  All rights reserved.</p>
    </div>
  </div>


  </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-dark" style="background-color: #00274C;">
  <div class="container-fluid">
     <a class="navbar-brand" href="#">
      <%= link_to image_tag('logo.gif'), root_path, class:"navbar-brand", alt:"Ethiopian Job Portal" %>
     </a> 	
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'My Jobs', jobs_find_my_jobs_path, class:"nav-link" %>
        </li>
        <% end  %>
        <li class="nav-item">
          <%= link_to 'Post a Job', new_job_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'CV Tips', home_cv_tips_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Interview Tips', home_interview_tips_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Profile
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to 'Change Password', edit_user_password_path, class:"dropdown-item" %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path, class:"dropdown-item" %></li>
            <% if !current_user.is_employer and !current_user.is_manager %>
              <li><%= link_to 'Upload CV', upload_cv_path, class:"dropdown-item" %></li>
            <% end  %>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class:"dropdown-item" %></li>
          </ul>

        </li>
            <% if current_user.is_manager %>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown12" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Configurations
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      
                      <li><%= link_to 'Career Levels', career_levels_path, class:"dropdown-item" %></li>
                      <li><%= link_to 'Employement Types', employement_types_path, class:"dropdown-item" %></li>
                      <li><%= link_to 'Employers', employers_path, class:"dropdown-item" %></li>
                      <li><%= link_to 'Job Categories', job_categories_path, class:"dropdown-item" %></li>
                      
                      <li><%= link_to 'Locations', destinations_path, class:"dropdown-item" %></li>

                    </ul>

                  </li>
            <% end  %>
        <% else  %>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
        </li>
        <% end  %>
       <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
      </ul>
     <form class="d-flex field form-group">
       <%= form_tag job_search_titles_path, method: 'get' do %>
         <input class="form-control me-2" type="search" id="search" placeholder="Search" aria-label="Search">
          <%= submit_tag("Search", class:"btn btn-outline-success") %> 

        <% end %>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_leftsidebar.html.erb
<div class="col-3">
    <table class="table table-responsive table-hover" width="100%">
       <thead class="table">           
            <tr>
              <th> Search any job in Ethiopia</th>
            </tr>
       </thead>
       <tbody>
           <% @job_categories.each do |job_category| %>
               <tr> 
                    <td style="text-align: right;">
                         <%= link_to job_category.name , jobs_find_by_category_path(JobCategory_id: job_category.id), class:"link-primary" %>
                    </td>
                    <td>
                       <span class="badge bg-primary" style="background-color: yellow;"> <%= Job.where("\"deadlineDate\" >= :date and \"JobCategory_id\" = :jobcategory and \"is_approved\"=true",  date: Date.today, jobcategory: job_category.id).count %> </span>
                    </td>
                </tr>
            <% end %>
      </tbody>
    </table>            
            
    </div>

app/views/layouts/_rightsidebar.html.erb
<div class="col">
        <table class="table table-responsive table-hover" width="100%">
       <thead>
            <tr>
              <th>Featured Jobs</th>
            </tr>
       </thead>
       <tbody>
         
        <% @featured_jobs.each do |featured_job| %>
           <tr> 
                <td>
                     <%= link_to featured_job.title , featured_job, class:"link-primary" %><br>

                     <%
                        if featured_job.Employer_id != nil 
                     %>
                        <%= Employer.where("id = ?" , featured_job.Employer_id).first.name %>
                     <%
                            end
                     %> 
                </td>
                
            </tr>
            
        <% end %>
      </tbody>
    </table>            
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon" type="image/ico" href="icon.ico"/>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <%= favicon_link_tag 'icon.ico' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Job Portal</title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
       .navbar-header .navbar-brand{
            max-width: 20px;
            max-height: 10%;
        }
    </style>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <br>
      <% if notice %>
          <%= render 'layouts/alerts' %>
      <% end %>
       <%= yield %>
    </div>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
    <%= render 'layouts/footer' %>
  </body>

</html>